Renewed Java testing infrastructure: now one test per source file / class

diff --git a/run-java b/run-java
--- a/run-java
+++ b/run-java
@@ -3,8 +3,9 @@
 . ./config
 
 TEST_FORMATS_JAVA_DIR=$(pwd)/compiled/java/src/io/kaitai/struct/testformats
+JAVA_SPEC_DIR=$(pwd)/spec/java/src/io/kaitai/struct/spec
 JAVA_CLASSES_DIR=$(pwd)/compiled/java/bin
-JAVA_BUILD_FAILS=$(pwd)/"$TEST_OUT_DIR"/build.fails
+JAVA_BUILD_FAILS=$(pwd)/"$TEST_OUT_DIR"/java/build.fails
 JAVA_COMPILE_LOG_DIR=$(pwd)/"$TEST_OUT_DIR"/java/compile_log
 
 # Compile everything:
@@ -23,7 +24,7 @@ echo "run-java: compiling binary format parser sources, generated by KS compiler
 javac -cp "$JAVA_CLASSES_DIR" \
 	"$TEST_FORMATS_JAVA_DIR"/*.java \
 	-d "$JAVA_CLASSES_DIR" || {
-	echo "run-java: some failed to compile, trying one by one"
+	echo "run-java: some formats failed to compile, trying one by one"
 	for TFJ in "$TEST_FORMATS_JAVA_DIR"/*.java; do
 		SRC=$(basename "$TFJ")
 		echo "$SRC"
@@ -35,11 +36,23 @@ javac -cp "$JAVA_CLASSES_DIR" \
 }
 
 # 3. Test specs
+# If this fails to compile as a group, try compiling individual files
+echo "run-java: compiling test specs"
 javac -cp "$JAVA_CLASSES_DIR:$JAVA_TESTNG_JAR" \
-	spec/java/src/io/kaitai/struct/spec/*.java \
-	-d "$JAVA_CLASSES_DIR"
+	"$JAVA_SPEC_DIR/"*.java \
+	-d "$JAVA_CLASSES_DIR" || {
+	echo "run-java: some test specs failed to compile, trying one by one"
+	for SPEC in "$JAVA_SPEC_DIR"/*.java; do
+		SRC=$(basename "$SPEC")
+		echo "$SRC"
+		(
+			javac -cp "$JAVA_CLASSES_DIR:$JAVA_TESTNG_JAR" "$SPEC" -d "$JAVA_CLASSES_DIR" 2>&1 ||
+			echo "$SRC" >>"$JAVA_BUILD_FAILS"
+		) | tee "$JAVA_COMPILE_LOG_DIR/$SRC.log"
+	done
+}
 
 # Actually run the tests
 cd spec/java
 java -cp "$JAVA_CLASSES_DIR:$JAVA_TESTNG_JAR" \
-	org.testng.TestNG -testclass io.kaitai.struct.spec.SpecTests -d "../../$TEST_OUT_DIR/java"
+	org.testng.TestNG -d "../../$TEST_OUT_DIR/java" testng.xml
