Added some support for MSVC

diff --git a/run-cpp_stl b/run-cpp_stl
--- a/run-cpp_stl
+++ b/run-cpp_stl
@@ -13,10 +13,19 @@ TEST_DIR=$(pwd)
 #rm -rf "$OBJ_DIR"
 mkdir -p "$OBJ_DIR"
 cd "$OBJ_DIR"
-if [ ! -r Makefile ]; then
-	cmake -DCMAKE_BUILD_TYPE=Debug "$TEST_DIR/spec/cpp_stl"
+if [ ! -r Makefile ] && [ ! -r Project.sln ]; then
+	cmake -DCMAKE_BUILD_TYPE=Debug "$KS_CMAKE_OPTIONS" "$TEST_DIR/spec/cpp_stl"
 fi
-make
+
+if [ -r Makefile ]; then
+	make
+elif [ -r Project.sln ]; then
+	msbuild
+else
+	echo "No build makefile/project file found, unable to continue."
+	ls -al
+	exit 1
+fi
 
 # Actually run the tests
 cd "$TEST_DIR"
