run-java: implemented partial compilation of step 2 with reporting of what exactly failed

diff --git a/run-java b/run-java
--- a/run-java
+++ b/run-java
@@ -2,17 +2,40 @@
 
 . ./config
 
+TEST_FORMATS_JAVA_DIR=$(pwd)/compiled/java/src/io/kaitai/struct/testformats
 JAVA_CLASSES_DIR=$(pwd)/compiled/java/bin
+JAVA_BUILD_FAILS=$(pwd)/"$TEST_OUT_DIR"/build.fails
+JAVA_COMPILE_LOG_DIR=$(pwd)/"$TEST_OUT_DIR"/java/compile_log
 
 # Compile everything:
-# 1. KS runtime part for Java
-# 2. Binary format parser sources, generated by KS compiler
-# 3. Test specs
+rm -f "$JAVA_BUILD_FAILS"
+rm -rf "$JAVA_COMPILE_LOG_DIR"
+mkdir -p "$JAVA_CLASSES_DIR" "$JAVA_COMPILE_LOG_DIR"
 
-mkdir -p "$JAVA_CLASSES_DIR"
-javac -cp $JAVA_TESTNG_JAR \
-	"$JAVA_RUNTIME_DIR/src/io/kaitai/struct/"*.java \
-	compiled/java/src/io/kaitai/struct/testformats/*.java \
+# 1. KS runtime part for Java
+# If this fails, there's no point to continue Java compilation
+echo "run-java: compling KS runtime part for Java"
+javac "$JAVA_RUNTIME_DIR/src/io/kaitai/struct/"*.java -d "$JAVA_CLASSES_DIR"
+
+# 2. Binary format parser sources, generated by KS compiler
+# If this fails to compile as a group, try compiling individual files
+echo "run-java: compiling binary format parser sources, generated by KS compiler"
+javac -cp "$JAVA_CLASSES_DIR" \
+	"$TEST_FORMATS_JAVA_DIR"/*.java \
+	-d "$JAVA_CLASSES_DIR" || {
+	echo "run-java: some failed to compile, trying one by one"
+	for TFJ in "$TEST_FORMATS_JAVA_DIR"/*.java; do
+		SRC=$(basename "$TFJ")
+		echo "$SRC"
+		(
+			javac -cp "$JAVA_CLASSES_DIR" "$TFJ" -d "$JAVA_CLASSES_DIR" 2>&1 ||
+			echo "$SRC" >>"$JAVA_BUILD_FAILS"
+		) | tee "$JAVA_COMPILE_LOG_DIR/$SRC.log"
+	done
+}
+
+# 3. Test specs
+javac -cp "$JAVA_CLASSES_DIR:$JAVA_TESTNG_JAR" \
 	spec/java/src/io/kaitai/struct/spec/*.java \
 	-d "$JAVA_CLASSES_DIR"
 
