Updated cpp_stl runners to properly handle 98+11 and work around build errors

diff --git a/run-cpp_stl b/run-cpp_stl
--- a/run-cpp_stl
+++ b/run-cpp_stl
@@ -12,29 +12,66 @@ CPP_SPEC_DIR="$2"
 CPP_TEST_OUT_DIR="$3"
 
 OBJ_DIR="$SRC_DIR/bin"
+SPEC_CMAKE="$OBJ_DIR/spec_files.cmake"
+COMPILED_CMAKE="$OBJ_DIR/compiled_files.cmake"
+ABS_CPP_TEST_OUT_DIR="$(pwd)/$CPP_TEST_OUT_DIR"
 TEST_DIR=$(pwd)
+
+# Create initial list of files to compile, starting with everything
+init_file_lists()
+{
+	rm -f "$SPEC_CMAKE"
+	echo 'set(SPEC_SOURCES' >>"$SPEC_CMAKE"
+	find "$CPP_SPEC_DIR" -name '*.cpp' >>"$SPEC_CMAKE"
+	echo ')' >>"$SPEC_CMAKE"
+
+	rm -f "$COMPILED_CMAKE"
+	echo 'set(KS_SOURCES' >>"$COMPILED_CMAKE"
+	find "$SRC_DIR" -name '*.cpp' >>"$COMPILED_CMAKE"
+	echo ')' >>"$COMPILED_CMAKE"
+}
+
+# Init CMake, generate platform-specific Makefile / project files
+init_cmake()
+{
+	#if [ ! -r Makefile ] && [ ! -r KS_TEST_CPP_STL.sln ]; then
+	echo "Using KS_CMAKE_OPTIONS=<$KS_CMAKE_OPTIONS>"
+	cmake -DCMAKE_BUILD_TYPE=Debug -DINC1_PATH="$SPEC_CMAKE" -DINC2_PATH="$COMPILED_CMAKE" "$KS_CMAKE_OPTIONS" "$CPP_SPEC_DIR"
+	#fi
+}
 
 # Compile everything:
 # 1. KS runtime part for C++/STL
 # 2. Binary format parser sources, generated by KS compiler
 # 3. Test specs
+compile_everything()
+{
+	echo 'Building project generated with CMake...'
+	if [ -r Makefile ]; then
+		make -j8 -k >"$ABS_CPP_TEST_OUT_DIR/make.stdout" 2>"$ABS_CPP_TEST_OUT_DIR/make.stderr"
+	elif [ -r KS_TEST_CPP_STL.sln ]; then
+		msbuild
+	else
+		echo "No build makefile/project file found, unable to continue."
+		ls -al
+		exit 1
+	fi
+}
 
 #rm -rf "$OBJ_DIR"
-mkdir -p "$OBJ_DIR"
+mkdir -p "$OBJ_DIR" "$ABS_CPP_TEST_OUT_DIR"
 cd "$OBJ_DIR"
-if [ ! -r Makefile ] && [ ! -r KS_TEST_CPP_STL.sln ]; then
-	echo "Using KS_CMAKE_OPTIONS=<$KS_CMAKE_OPTIONS>"
-	cmake -DCMAKE_BUILD_TYPE=Debug -DKS_PATH="$SRC_DIR" "$KS_CMAKE_OPTIONS" "$CPP_SPEC_DIR"
-fi
 
-if [ -r Makefile ]; then
-	make -j8
-elif [ -r KS_TEST_CPP_STL.sln ]; then
-	msbuild
+init_file_lists
+
+init_cmake
+if compile_everything; then
+	# all good, compile finished
+	true
 else
-	echo "No build makefile/project file found, unable to continue."
-	ls -al
-	exit 1
+	# try to fix up by removing some files from compilation
+	echo 'Trying to resolve by linking successfully compiled things...'
+	"$TEST_DIR/link-cpp_stl" "." "$ABS_CPP_TEST_OUT_DIR"
 fi
 
 # Work around boost v1.62 bug: https://svn.boost.org/trac10/ticket/12507
@@ -54,7 +91,6 @@ fi
 
 # Actually run the tests
 cd "$TEST_DIR"
-mkdir -p "$CPP_TEST_OUT_DIR"
 "$OBJ_DIR/ks_tests" \
 	--log_format=XML \
 	$BOOST_LOG_OPTION \
